import pandas as pd, numpy as np, matplotlib.pyplot as plt, logging, json, os
from datetime import datetime
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")

class ReportGenerator:
    def __init__(s, output_dir="reports", benchmark=0.08):
        s.output_dir, s.benchmark = output_dir, benchmark
        os.makedirs(output_dir, exist_ok=True)
    
    def generate(s, equity, trades, params, metrics, symbol="PORTFOLIO"):
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        base = s.output_dir + "/" + symbol + "_" + ts
        
        # 1. 保存交易明细
        if trades:
            pd.DataFrame(trades).to_csv(base+"_trades.csv", index=False)
            logging.info("📋 交易明细: "+base+"_trades.csv")
        
        # 2. 绘制 Equity Curve
        s._plot_equity(equity, s.benchmark, base+"_equity.png", symbol)
        
        # 3. 生成 Markdown 报告
        s._generate_md(base+".md", metrics, params, len(trades), symbol)
        
        # 4. 生成 JSON 摘要
        with open(base+"_summary.json", "w") as f:
            json.dump({"metrics": metrics, "params": params, "trade_count": len(trades)}, f, indent=2, default=str)
        
        logging.info("📄 报告已生成: "+base+".md")
        return base
    
    def _plot_equity(s, equity, bench_ann, path, symbol):
        eq = pd.Series(equity)
        dates = pd.date_range(end=datetime.now(), periods=len(eq), freq="h")
        bench = [100000 * (1 + bench_ann/252/6)**i for i in range(len(eq))]
        plt.figure(figsize=(10,5))
        plt.plot(dates, eq, label=symbol+" Equity", linewidth=2)
        plt.plot(dates, bench, label="Benchmark", linestyle="--", alpha=0.7)
        plt.title(symbol+" Backtest"); plt.xlabel("Time"); plt.ylabel("Value")
        plt.legend(); plt.grid(alpha=0.3); plt.xticks(rotation=30)
        plt.tight_layout(); plt.savefig(path, dpi=120); plt.close()
        logging.info("📈 Equity Curve: "+path)
    
    def _generate_md(s, path, metrics, params, trade_count, symbol):
        lines = [
            "# "+symbol+" Backtest Report",
            "**Generated**: "+datetime.now().strftime("%Y-%m-%d %H:%M"),
            "",
            "## Key Metrics",
            "| Metric | Value |",
            "|--------|-------|",
            "| Total Return | "+str(metrics.get("total_return","N/A"))+" |",
            "| Sharpe | "+str(metrics.get("sharpe","N/A"))+" |",
            "| Max Drawdown | "+str(metrics.get("max_drawdown","N/A"))+" |",
            "| Win Rate | "+str(metrics.get("win_rate","N/A"))+" |",
            "| Trades | "+str(trade_count)+" |",
            "",
            "## Parameters",
            "```",
            str(params),
            "```",
            "",
            "> Report generated by Fed-Trading 2.1"
        ]
        with open(path, "w") as f:
            f.write("\n".join(lines))
